### ISSUE TITLE
getLastRoute Error

### ISSUE THREAD

**Issue by braggj5279** [pathway-team/pathway-android#20]
Calling getLastRoute() produces a SQL error.

android.database.sqlite.SQLiteException: near "1": syntax error (code 1): , while compiling: SELECT TOP 1 json_str FROM tbl_routes ORDER BY id DESC

**Comment by eewest** [comment]
Should be fixed rewrote query to fix error.

**Comment by eewest** [comment]
Fixed issue. Problem was the limited keywords of SQLite databases. For now will pull the whole database in reverse order and return the first element of the query.
